---
title: "bird_hp3_v1"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

Filtered/selected the virus-specific fields to become virus sheet of HP3

```{r filter virus, echo=FALSE}
hp3_virus<-select(bird.hp3_presort, Virus_Order:Jones)
View(hp3_virus)
write.csv(hp3_virus, file = "bird_hp3_virus.csv")
```

```{r filter host, echo=FALSE}
hp3_host<-select(bird.hp3_presort, X, Host_Common_Name:total_host_pubs, Wild_Dom:Wild_Dom_code, Geographical_Origin:Notes)
View(hp3_host)
write.csv(hp3_host, file = "bird_hp3_host.csv")
```

```{r filter host_virus, echo=FALSE}
hp3_host_virus<-select(bird.hp3_presort, X, Virus_Species, Host_Common_Name, Genus_species, Detection:Detection_code, Vector:Other_hosts, Geographical_Origin, Reference:Notes)
write.csv(hp3_host_virus, file = "bird_hp3_host_virus.csv")
```

```{r rename virus columns, echo=FALSE}
hp3_virus<-rename(hp3_virus, old_vOrder=Virus_Order)
hp3_virus<-rename(hp3_virus, old_vFamily=Virus_Family, old_vFam_Pubs=virfam_pubs, old_vGenus=Virus_Genus, old_vPubs=Vir_pubs)
View(hp3_virus)
```

```{r deleting duplicate viruses, echo=FALSE}
hp3_virus<-distinct(hp3_virus)
```

```{r merging ictv 2015 with hp3_virus, echo=FALSE}
hp3_virus_updated<-full_join(hp3_virus, bird_viruses_ictv_2009_v_2015, by = "ICTV_2009_Species")
```

```{r reordering new hp3_virus_updated, echo=FALSE}
hp3_virus_updated<-full_join(hp3_virus, bird_viruses_ictv_2009_v_2015, by = "ICTV_2009_Species")
```

had to correct for typos and rerun code. reran as following:
```{r from bird_hp3_virus.csv to merged virus dataframe, echo=FALSE}
hp3_virus<-select(bird_hp3_virus, Virus_Order:Jones)
hp3_virus<-rename(hp3_virus, old_vOrder=Virus_Order)
hp3_virus<-rename(hp3_virus, old_vFamily=Virus_Family, old_vFam_Pubs=virfam_pubs, old_vGenus=Virus_Genus, old_vPubs=Vir_pubs)
hp3_virus<-distinct(hp3_virus)
hp3_virus_updated<-full_join(hp3_virus, bird_viruses_ictv_2009_v_2015, by = "ICTV_2009_Species")
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
